### ISSUE TITLE
NameError: name 'get_crypt' is not defined also ubale to connect to remote server ip

### ISSUE THREAD

**Issue by arjuntpoyilil** [nakagami/pyfirebirdsql#106] opened 2024-06-22 12:04 UTC
NameError: name 'get_crypt' is not defined

(myenv) D:\Work\My Jupyter Notebook>py lambda_function.py
Traceback (most recent call last):
  File "D:\Work\My Jupyter Notebook\lambda_function.py", line 3, in <module>
    conn = firebirdsql.connect(
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Work\My Jupyter Notebook\myenv\Lib\site-packages\firebirdsql\__init__.py", line 141, in connect
    conn = Connection(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Work\My Jupyter Notebook\myenv\Lib\site-packages\firebirdsql\fbcore.py", line 962, in __init__
    self._parse_connect_response()
  File "D:\Work\My Jupyter Notebook\myenv\Lib\site-packages\firebirdsql\fbcore.py", line 728, in _parse_connect_response
    auth_data = self.str_to_bytes(get_crypt(self.password))
                                  ^^^^^^^^^
NameError: name 'get_crypt' is not defined

**Comment by 66zai** [comment] 2024-06-22 12:05
This is an automatic reply, confirming that your e-mail was received.Thank you----------------------------------------------------------您的E-mail我已经收到，如果看到定会很快给您答复。

**Comment by nakagami** [comment] 2024-06-22 12:49
Oh,

**Comment by arjuntpoyilil** [comment] 2024-06-22 13:24
Thank you it working now but i wtill have issue connecting remote IP 

but same code working fine with FDB and firebird-driver 

please note the server i connecting has some restiction and only open port is 3050,  i am note sure what protocall is using pyfirebirdsql to connect remote server 

(myenv) D:\Work\My Jupyter Notebook>py lambda_function.py
Traceback (most recent call last):
  File "D:\Work\My Jupyter Notebook\lambda_function.py", line 3, in <module>
    conn = firebirdsql.connect(
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Work\My Jupyter Notebook\myenv\Lib\site-packages\firebirdsql\__init__.py", line 94, in connect
    conn._initialize_socket()
  File "D:\Work\My Jupyter Notebook\myenv\Lib\site-packages\firebirdsql\fbcore.py", line 983, in _initialize_socket
    raise e
  File "D:\Work\My Jupyter Notebook\myenv\Lib\site-packages\firebirdsql\fbcore.py", line 979, in _initialize_socket
    self._parse_connect_response()
  File "D:\Work\My Jupyter Notebook\myenv\Lib\site-packages\firebirdsql\fbcore.py", line 755, in _parse_connect_response
    (h, oid, buf) = self._op_response()
                    ^^^^^^^^^^^^^^^^^^^
  File "D:\Work\My Jupyter Notebook\myenv\Lib\site-packages\firebirdsql\fbcore.py", line 654, in _op_response
    raise OperationalError('Unauthorized')
firebirdsql.err.OperationalError: Unauthorized

**Comment by nakagami** [comment] 2024-06-22 13:33
Driver seems to be working as intended.

Incidentally, the Driver expects the user registered in Firebird to be upper case.For example

hajime -> HAJIME

**Comment by arjuntpoyilil** [comment] 2024-06-22 13:38
Yes the given User name is upper case and it working in my local system as well but not working when connecting to remote server IP and port using pyfirebirdsql

**Comment by nakagami** [comment] 2024-06-22 13:43
I think the port number is ok.

`Unauthorized` is returned by the server.

Is your Firebird version 2.5 or higher?

Sorry, I don't know any more.
Does anyone have any idea what's going on with Windows?

**Comment by arjuntpoyilil** [comment] 2024-06-22 13:47
The Firebird version in the server is 3.0.1133703, I hope it doesn't matter what FB version is used in my local system is 4.0.2

**Comment by nakagami** [comment] 2024-06-22 13:51
One thing I remember.

passlib https://pypi.org/project/passlib/ would need to be installed.
But sorry, I have never tested this combination on Windows.

If you have Firebird 3.0, try Srp or Srp256 authentication
If this doesn't work for you.
Please configure your firebird.conf to allow Srp or Srp256 authentication

**Comment by arjuntpoyilil** [comment] 2024-06-22 13:54
Still same issue 

server FB config 

ServerMode = Super   

DefaultDbCachePages = 50K  
FileSystemCacheThreshold = 999M 
TempCacheLimit  =4682M
LockHashSlots = 49999           
TempBlockSize = 2M           
MaxUnflushedWrites = -1        
MaxUnflushedWriteTime = -1   

WireCrypt = Enabled
RemoteServicePort = 3050
AuthServer = Legacy_Auth, Srp, Win_Sspi
AuthClient = Legacy_Auth, Srp, Win_Sspi
UserManager = Srp, Legacy_UserManager

**Comment by nakagami** [comment] 2024-06-22 14:01
Sorry, Legacy_Auth may not work well in windows.

escribing it in this way may work
```
AuthServer = Srp,Legacy_Auth,Win_Sspi
```

**Comment by nakagami** [comment] 2024-06-22 14:28
There was a bug in Legacy_Auth using passlib. (Windows uses passlib)
Now fixed.

**Comment by arjuntpoyilil** [comment] 2024-06-22 14:37
In my system, I checked it was only working with Srp256, but I didn't get a chance to check in the server, i will test it at midnight(IST), In FB 4(my system) by default Srp25 was enabled

**Comment by nakagami** [comment] 2024-06-22 14:45
Thanks, I look forward to your test results with Srp 256.

BTW, before change firebird.conf,
Install the latest driver again.
(with this fix https://github.com/nakagami/pyfirebirdsql/commit/78e104147d17fd8736bd942e9d47cc2f74808022 )
What happens if you try it?

**Comment by arjuntpoyilil** [comment] 2024-06-22 15:10
Error in my local system

**Legacy_Auth**

firebirdsql.err.OperationalError: Your user name and password are not defined. Ask your database administrator to set up a Firebird login.

**Win_Sspi**

firebirdsql.err.OperationalError: Error occurred during login, please check server firebird.log for details

**Srp256 and Srp**

both working without any issue

**Comment by nakagami** [comment] 2024-06-23 00:03
Thanks

I'm glad it works in your environment. ( Srp256 and Srp)

I wonder if anyone else can't get it to work on Windows + Legacy_Auth.

Also in my environment, It didn't work with Legacy_Auth, but I fixed it and it works now, so I'm uploading it to pypi as a new version once, although it may be incomplete.

**Closed** 2024-06-23 00:19 UTC

**Comment by arjuntpoyilil** [comment] 2024-06-24 06:47
I have tested Srp256 and Srp in my Windows server, and they are working well along with my other apps. Therefore, I am no longer concerned about Legacy_Auth and Win_Sspi. Perhaps you can include this information in the Windows requirement documentation. 
Thank you so much. Keep up the good work!
